on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    env:
      LLVM_DIR: .llvm
      LLVM_URL: https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0-rc2/clang+llvm-14.0.0-rc2-aarch64-linux-gnu.tar.xz

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache clang-format
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/${{ env.LLVM_DIR }}
          key: ${{ env.LLVM_URL }}

      - name: Install clang-format
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          mkdir -p "${RUNNER_TEMP}/${LLVM_DIR}"
          wget -q -O- "${LLVM_URL}" | tar -xJ --strip-components=2 --wildcards -C "${RUNNER_TEMP}/${LLVM_DIR}" '*/bin/clang-format'

      - name: Add clang-format to PATH
        run: echo "${RUNNER_TEMP}/${LLVM_DIR}" >> $GITHUB_PATH

      - uses: pre-commit/action@v2.0.3
